config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :meals do
    resources :reviews, only: [:create]
    resources :orders, only: [:create]
  end

  get 'accept/order/:id', to: 'orders#accept'
  get 'reject/order/:id', to: 'orders#reject'

  get '/dashboard', to: 'user#dashboard'


  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_attachment :photo
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def avg_rating
    self.reviews.empty? ? 0 : (self.reviews.map{ |r| r.rating }.reduce(:+) / self.reviews.length)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :meal

  validates :user, presence: true
  validates :meal, presence: true
  validates :time, presence: true
  validates :portions, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :meal
  belongs_to :user

  validates :comment, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  before_validation :strip_whitespace
  has_many :meals, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :password,
  presence: true,
  format: { with: /\A(?=.*[a-zA-Z])(?=.*[0-9]).{6,}\z/ }

  def full_name
    return "#{self.first_name} #{self.last_name}"
  end


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  private

  def strip_whitespace
    self.email = email.strip unless email.nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number])
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_meal, only: [:edit, :update, :destroy]

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    if @meal.save
      redirect_to meal_path(@meal)
    else
      render :new
    end
  end

  def index
   if params[:search].present?

      @meals = Meal.near(params[:search], 10)
      @results = Geocoder.coordinates(params[:search])
      # if params address
      # geocode that address
      # find meals near geocoded address
      # else do
    else
      @meals = Meal.where.not(latitude: nil, longitude: nil)
    end

    @hash = Gmaps4rails.build_markers(@meals) do |meal, marker|
      marker.lat meal.latitude
      marker.lng meal.longitude
      # marker.infowindow render_to_string(partial: "/meals/map_box", locals: { meal: meal })
    end
  end

  def show
    @meal = Meal.find(params[:id])
    @meal_coordinates = { lat: @meal.latitude, lng: @meal.longitude }
    @review = Review.new
  end

  def edit
  end

  def update
    if @meal.update(meal_params)
     redirect_to meal_path(@meal)
    else
      render :new
    end
  end


  def destroy
    @meal.destroy
    redirect_to dashboard_path
  end

  private
  def set_meal
    @meal = Meal.find(params[:id])
    if current_user != @meal.user
      redirect_to root_path
    end
  end

  def meal_params
    params.require(:meal).permit(:name, :price, :address, :category, :description, :photo)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @order = Order.new(order_params)
    @order.time += ' - ' + Date.today.strftime('%A, %b %d')
    @order.user = current_user
    @order.meal = Meal.find(params[:meal_id])
    @order.status = "Pending"
    if @order.save
      redirect_to dashboard_path
    else
      render meal_path(@order.meal)
    end
  end

  def accept
    @order = Order.find(params[:id])
    @order.update(status: "Accepted")
    redirect_to dashboard_path
  end

  def reject
    @order = Order.find(params[:id])
    @order.update(status: "Rejected")
    redirect_to dashboard_path
  end

  private

  def order_params
    params.require(:order).permit(:time, :portions)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
def create
    @review = Review.new(reviews_params)
    @review.user = User.find(current_user.id)
    @review.meal = Meal.find(params[:meal_id])
    if @review.save
      redirect_to meal_path(@review.meal)
    else
      render 'meals/show', locals: { id: @review.meal.id }
    end
  end

  private
  def reviews_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def dashboard
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Cooking Mama</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield(:sidebar) %>
    <div style="padding-top: 70px;">
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>

    <!--These lines are required to call google maps api-->

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= simple_form_for(@meal) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: "Meal's name", placeholder: "Hector's Veggie Pizza" %>
  <%= f.input :photo, label: "Photo (Large picture is better!)", as: :attachinary %>
  <%= f.input :price, label: "Price", placeholder: "$10" %>
  <%= f.input :address, label: "Pick-up address", placeholder: "5333 avenue Casgrain, Montréal" %>
  <%= f.input :category, label: "Meal's category", placeholder: "Food-Porn, Veggie, Gluten-free..." %>
  <%= f.input :description, label: "Ingredients", placeholder: "A lot of tomatos, and I really don't know what kind of veggie stuff you can put in a Pizza" %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/meals/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2 class="text-center">Update your meal, Mama!</h2>
      <%= render 'form' %>
      <%= link_to 'Back', :back %>
    </div>
  </div>
</div>

app/views/meals/index.html.erb
<div class="meals-container meals">
  <div class="card-container">
  <h2 class="text-center">These are the meals close to you</h2>
    <div class="row">
      <% @meals.each do |meal| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="meal-card">
            <%= link_to '', meal_path(meal), class: 'card-link' %>
            <div class="meal-content">

              <div class="meal-img" style="background-image: url('<%= cl_image_path meal.photo.path if meal.photo? %>')">
              </div>

              <div class="meal-head">
                <h5><b><%= meal.name %></b></h5>
              </div>
              <div class="meal-info">
                <p><%= meal.category %></p>
                <p>
                  <%meal.avg_rating.times { %><i class='fa fa-star'></i> <% } %>
                  <%(5 - meal.avg_rating).times { %><i class='fa fa-star-o'></i> <% } %>
                </p>
              </div>
              <div class="meal-bottom-elements">
                <div class="meal-price">
                  <p>$ <%= meal.price %></p>
                </div>
                <div class="meal-order" style="z-index: 1">
                  <%= link_to 'order', meal_path(meal), class: 'btn btn-primary' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div id="map" style="width: 100%; height: calc(100vh - 70px);"></div>


  <% content_for(:after_js) do %>
    <%= javascript_tag do %>

      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        <% unless @results.nil? %>
        positionMarker = handler.addMarkers([
        { "lat": <%= @results.first %>,
          "lng": <%= @results.last %>,
          "picture": {
            "url": "<%= asset_path("oval.png") %>",
            "width": 32,
            "height": 32
          },
        }
        ]);
        handler.bounds.extendWith(positionMarker);
        <% end %>
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    <% end %>
  <% end %>
</div>

app/views/meals/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2 class="text-center">Create your meal, Mama!</h2>
      <%= render 'form' %>
      <%= link_to 'Back', :back %>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<% @meal   = @meal.nil? ? Meal.find(id) : @meal %>
<% @review = @review.nil? ? Review.new : @review %>
<% @order  = @order.nil? ? Order.new : @order %>

<div class="container">

  <div class="row up-division">
    <div class="col-xs-12 col-sm-6">
      <div class="meal-image" style="background-image: url('<%= cl_image_path @meal.photo.path if @meal.photo? %>')"></div>
      <p class="text-center"><b>Made by</b> <%= @meal.user.first_name + ' ' + @meal.user.last_name %></p>
      <div class="meal-info">
        <div class="meal-info">
          <div class="meal-description text-justify">
            <h3>Description</h3>
            <p><%= @meal.description %></p>
          </div>
          <p><b>Category:</b> <%= @meal.category %></p>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6">
      <h2><%= @meal.name %> - $<%= @meal.price %></h2>
      <% if current_user != @meal.user %>
        <% if user_signed_in? %>
          <%= simple_form_for([@meal, @order]) do |f| %>
            <div class="formy">
              <div class="formy-item">
                <%= f.input :time, labe: "Pickup time", as: :select, collection: (24.times.map { |i| "#{i}:00" }), selected: :first %>
              </div>
              <div class="formy-item">
                <%= f.input :portions, input_html: { min: 1, max: 10, step: 1, value: 1} %>
              </div>
              <div class="formy-item">
                <%= f.submit "Order now!", class: "btn btn-success btn-lg" %>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= link_to 'Login to Order',  new_user_session_path, class: 'btn btn-primary btn-lg' %>
        <% end %>
      <% end %>
      <p><b>Address:</b> <%= @meal.address %></p>
    </div>
  </div>

  <div class="row down-division">
    <!-- Showing Reviews -->
    <% if user_signed_in? && current_user != @meal.user %>
      <div class="col-xs-12 col-sm-6">
    <% else %>
      <div class="col-xs-12">
    <% end %>
      <h4 class="text-center">Reviews</h4>
       <% if @meal.reviews.size == 0 %>
        <h4 class="text-center"> Be the first to review this Meal!</h4>
      <% end %>
      <% @meal.reviews.each do |review| %>
        <div class="review-card">
          <p><%= review.comment %></p>
          <p>
            <%review.rating.times { %><i class='fa fa-star'></i> <% } %>
            <%(5 - review.rating).times { %><i class='fa fa-star-o'></i> <% } %>
          </p>
          <p><i><%= review.user.full_name %></i></p>
        </div>
      <% end %>
    </div>

    <!-- Review form -->
    <% if user_signed_in? && current_user != @meal.user %>

      <!-- Show review because user is singed in and he/she is not the chef -->
      <div class="col-xs-12 col-sm-4 col-sm-offset-1">
        <h4 class="text-center">Add a review</h4>
        <% if @review.errors.any? %>
          <ul>
            <% @review.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= simple_form_for([@meal, @review]) do |f| %>
          <%= f.input :comment %>
          <%= f.input :rating, collection: 0..5 %>
          <%= f.submit class: "btn btn-primary" %>
        <% end %>
      </div>

    <% elsif !user_signed_in? %>

      <!-- Show "Login first" message because user is not logged in -->
      <% if @meal.reviews.size == 0 %>
        <div class="col-xs-12">
      <% else %>
        <div class="col-xs-12 col-sm-4 col-sm-offset-1">
      <% end %>
        <h4 class="text-center">You need to log in to write a review</h4>
      </div>

    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<h2 class="text-center">HOW IT WORKS</h2>

<div class="flex-container">
  <div class="row text-center">
    <div class="col-xs-4">
      <%= image_tag "student.png", class: "welcomeimg" %>
      <h3>Order.</h3>
      <p class="text-info">
        Find meals that fit your taste, location, and price.
      </p>
    </div>
    <div class="col-xs-4">
      <%= image_tag "take-away.png", class: "welcomeimg" %>
      <h3>Pick up.</h3>
      <p class="text-info">
        Stop by your neighborhood cook’s home to pick up your meal.
      </p>
    </div>
    <div class="col-xs-4">
      <%= image_tag "boy.png", class: "welcomeimg" %>
      <h3>Enjoy!</h3>
      <p class="text-info">
        Take it home and feast!
      </p>
    </div>
  </div>
</div>



<%= render 'shared/banner2' %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://static.pexels.com/photos/11415/befa5c7cfca376be94eddaf5af8d72f6.jpg');">
  <div class="banner-content">
    <h1>COOKING MAMA</h1>
    <p>Pick it up it's ready!</p>
    <form class="form-inline" action='/meals'>
      <div class="form-group form-banner">
        <input id="meal_address" placeholder="Enter your address"
        onFocus="geolocate()" name="search" class="form-control address-input" type="text"></input>
        <button type="submit" class="btn-banner btn btn-md">Search</button>
      </div>
    </form>
  </div>
</div>

app/views/shared/_banner2.html.erb
<div class="banner2" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://static.pexels.com/photos/361184/asparagus-steak-veal-steak-veal-361184.jpeg');">

  <% if user_signed_in? %>
    <h5 class="text text-center"> It's your turn to start earning some money. You can become the hot new spot in your neighborhood!</h5>
    <p> <%= link_to "START COOKING", new_meal_path, class: "banner2link" %> </p>
  <% else %>
    <h3 class="text text-center"> Explore home cooked food around you.</h3>
    <p> <%= link_to "SIGN UP", new_user_session_path, class: "banner2link" %> </p>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-links"> Contact us
    <a href="https://www.instagram.com/neddstarr"><i class="fa fa-instagram"></i></a>
    <a href="https://www.facebook.com/robin.handous"><i class="fa fa-facebook"></i></a>
    <a href="https://www.linkedin.com/in/rafaelalonso42/"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer__disclaimer">© 2017 Cooking Mama inc</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <span>COOKING MAMA</span>
    <%= image_tag "cookingmama1.png", class: "navmama" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Cook for us", new_meal_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t(".profile", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to new_meal_path do %>
            <i class="fa fa-cutlery"></i> <%= t(".profile", default: "Cook for Us") %>
          <% end %>
        </li>
        <li>
          <%= link_to dashboard_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-cog"></i>  <%= t(".profile", default: "Settings") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/user/_history.html.erb
<h2 class="text-center">This is the history of the meals you ordered!</h2>

<% current_user.orders.reverse.first(5).each do |order| %>
  <div class="order">
    <%= link_to '', meal_path(order.meal), class: 'list-link' %>
    <div class="order-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path order.meal.photo.path, height: 150, width: 205, crop: :scale if order.meal.photo? %>')">
    </div>
    <div class='order-body'>
      <h3><%= order.meal.name %> ($<%= order.meal.price %>)</h3>
      <p>Chef: <%= order.meal.user.first_name %></p>
      <h6><i class="fa fa-clock-o"> <%= order.time %></i></h6>
      <h6><%= order.portions %> Portion(s)</h6>
    </div>
    <div class="order-controls hidden-sm hidden-xs">
      <% if order.status == "Accepted" %>
        <h5 class="text-center green"><%= order.status %></h5>
      <% elsif order.status == "Rejected" %>
        <h5 class="text-center red"><%= order.status %></h5>
      <% else %>
        <h5 class="text-center"><%= order.status %></h5>
      <% end %>
    </div>
  </div>
<% end %>

app/views/user/_meals.html.erb
<h2 class="text-center">This are the meals that you made!</h2>
<div class="row text-center meals">
  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="meal-card">
      <%= link_to '',  new_meal_path, class: 'card-link' %>
      <div class="meal-content">

        <div class="meal-img">
          <i class="fa fa-plus-circle" style="font-size: 70px;"></i>
        </div>

        <div class="meal-head">
          <h5><b>New Meal</b></h5>
        </div>
      </div>
    </div>
  </div>
  <% current_user.meals.each do |meal| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="meal-card">
        <%= link_to '', meal_path(meal), class: 'card-link' %>
        <div class="meal-content">

          <div class="meal-img" style="background-image: url('<%= cl_image_path meal.photo.path if meal.photo? %>')">
          </div>

          <div class="meal-head">
            <h5><b><%= meal.name %></b></h5>
          </div>

          <div class="meal-info">
            <p><%= meal.category %></p>
            <p>
              <%meal.avg_rating.times { %><i class='fa fa-star'></i> <% } %>
              <%(5 - meal.avg_rating).times { %><i class='fa fa-star-o'></i> <% } %>
            </p>
          </div>

          <div class="meal-bottom-elements", style="padding: 10px 20px; z-index: 1;">
            <%= link_to "Edit", edit_meal_path(meal), class: 'btn btn-warning btn-sm' %>
            <%= link_to "Delete", meal_path(meal), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure? You won\'t be able to restore it!'} %>
          </div>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user/_orders.html.erb
<h2 class="text-center">These are the meals people are ordering from you!</h2>

<% Order.where(meal: current_user.meals).reverse.first(5).each do |order| %>
  <div class="order">
    <%= link_to '', meal_path(order.meal), class: 'list-link' %>
    <div class="order-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path order.meal.photo.path, height: 150, width: 205, crop: :scale if order.meal.photo? %>')">
    </div>
    <div class='order-body'>
      <h3><%= order.meal.name %> ($<%= order.meal.price %>)</h3>
      <p>Ordered by: <%= order.user.first_name %></p>
      <h6><i class="fa fa-clock-o"> <%= order.time %></i></h6>
      <h6><%= order.portions %> Portion(s)</h6>
    </div>
    <div class="order-controls hidden-sm hidden-xs" style="z-index: 1">
      <% if order.status == "Accepted" %>
        <h5 class="text-center green"><%= order.status %></h5>
      <% elsif order.status == "Rejected" %>
        <h5 class="text-center red"><%= order.status %></h5>
      <% else %>
        <h5 class="text-center"><%= order.status %></h5>
        <ul class="list-inline">
          <li><%= link_to "Accept", "accept/order/#{order.id}", class: 'btn btn-success btn-sm' %></li>
          <li><%= link_to "Reject", "reject/order/#{order.id}", class: 'btn btn-danger btn-sm' %></li>
        </ul>
      <% end %>
    </div>
  </div>
<% end %>

app/views/user/dashboard.html.erb
<style>
  .container {
    margin-left: 200px; /* Same as the width of the tab */
    width: calc(100% - 200px);
  }
</style>

<% content_for(:sidebar) do %>
  <div id="mySidenav" class="tab">
    <span class="tablinks" onclick="openCity(event, 'Orders')" id="defaultOpen">Orders</span>
    <span class="tablinks" onclick="openCity(event, 'History')">History</span>
    <span class="tablinks" onclick="openCity(event, 'Meals')">Your meals</span>
  </div>
<% end %>

<div class="container">

  <div class="dash-view tabcontent" id="Orders">
    <%= render 'orders' %>
  </div>

  <div class="dash-view tabcontent" id="History">
    <%= render 'history' %>
  </div>

  <div class="dash-view tabcontent" id="Meals">
    <%= render 'meals' %>
  </div>

</div>